# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{string_replacer}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Seamus Abshere"]
  s.date = %q{2010-09-22}
  s.default_executable = %q{string_replacer}
  s.description = %q{For example, if you need to make sure that a particular package is unmasked in /etc/portage/package.keywords/local, you can use string_replacer to put it there without disturbing the other lines.}
  s.email = %q{seamus@abshere.net}
  s.executables = ["string_replacer"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/string_replacer",
     "lib/string_replacer.rb",
     "test/helper.rb",
     "test/test_string_replacer.rb"
  ]
  s.homepage = %q{http://github.com/seamusabshere/string_replacer}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Repeatedly replace text in a file without disturbing the rest of the file.}
  s.test_files = [
    "test/helper.rb",
     "test/test_string_replacer.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

